### ISSUE TITLE
Améliorations du dépôt

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#137]
## Labels
- [ ] Création d'un label `Violation délibérée`, pour quand un utilisateur traîne des pieds à se conformer, ou que le cas devient sérieux.
- [ ] Création d'un label `Concerne ce dépôt`, pour les demandes comme celle-ci qui ne sont pas des signalements.

## Autres
Centralisation des autres travaux ou idées.
- [ ] Réparation du [nouveau modèle](https://github.com/osm-fr/attributions/blob/main/.github/ISSUE_TEMPLATE/experimental-issue.yml) .yml (inutilisable pour le moment)
- [ ] Rechercher comme définir des labels automatiquement — #110
- [ ] Essayer une autre approche que les cases à cocher — #56
- [ ] Trancher parmi les modèles que l'on garde ou non — #56

**Comment by Altonss** [comment]
Cette issue a aussi un lien avec cette ancienne ici: https://github.com/osm-fr/attributions/issues/4

**Comment by AntoninCurtit** [comment]
(J'ai pu créer les labels)

Selon moi, cette issue-là ne sert plus maintenant, pour les templates le boulot est globalement fait et pour le reste il n'y a pas de tâches « à faire » ni de débat nécessitant de la relier à issue-ci.

**Comment by Altonss** [comment]
> Selon moi, cette issue-là ne sert plus maintenant, pour les templates le boulot est globalement fait et pour le reste il n'y a pas de tâches « à faire » ni de débat nécessitant de la relier à issue-ci.

Je vais donc fermer #4 si elle ne sert plus. Libre a qqn de la rouvrir si il en ressent le besoin :)

**Comment by vinber** [comment]
bonjour,
merci pour le boulot que vous faites.
Je suis partagé sur Violation délibérée, je trouve les critères "pour quand un utilisateur traîne des pieds à se conformer, ou que le cas devient sérieux." assez complexe à définir. Selon moi à manipuler avec attention et précaution :)

**Comment by Altonss** [comment]
> Je suis partagé sur Violation délibérée, je trouve les critères "pour quand un utilisateur traîne des pieds à se conformer, ou que le cas devient sérieux." assez complexe à définir. Selon moi à manipuler avec attention et précaution :)

Totalement d'accord, à manipuler avec précaution et une fois seulement que l'on en a discuté et qu'il y a un certain consensus :)

**Comment by vinber** [comment]
Si on regarde les diverses issues de ce dépot beaucoup prennent du temps.
- https://github.com/osm-fr/attributions/issues/10 par exemple, bon ok c'est long mais visiblement cela galère fort si déja ils ont des soucis sur leur adresse mail admin 
- "cas sérieux nécessite une action de la communauté" sur le label Violation délibérée ne me semble pas appropriée non plus, tous les cas sont sérieux, nécessite une action puisqu'ils sont dans ce dépot
- je pencherai davantage par exemple pour + d'un an, un label de durée sans rien faire

**Comment by Altonss** [comment]
Oui ça me parait bien comme modification!
On pourrait aussi ajouter, de nombreuses relances et aucune réponse/action depuis une longue durée (ex 1 an).
Je vous laisse modifier la description, je n'ai pas accès à cela je crois ^^

**Comment by AntoninCurtit** [comment]
Perso je ne vois pas le mal, ça n'est pas parce que le label est définie que l'utilisateur se retrouve immédiatement assigné à comparaître.

Totalement d'accord pour qu'il faille l'utiliser avec parcimonie, et des critères, mais ce label est aussi un appel de pied à la communauté ; "X ne se conforme pas, j'ai besoin de vos avis, et soutiens".
Un peu un constat du "je n'y suis pas arrivé seul, la communauté doit m'aider".

**Comment by AntoninCurtit** [comment]
> Si on regarde les diverses issues de ce dépot beaucoup prennent du temps.
> - https://github.com/osm-fr/attributions/issues/10 par exemple, bon ok c'est long mais visiblement cela galère fort si déja ils ont des soucis sur leur adresse mail admin 
> - "cas sérieux nécessite une action de la communauté" sur le label Violation délibérée ne me semble pas appropriée non plus, tous les cas sont sérieux, nécessite une action puisqu'ils sont dans ce dépot

Sérieux au point : "J'ai signalé, relancé, ça n'a pas été corrigé". On est pas sur un oubli, c'est volontaire.

> - je pencherai davantage par exemple pour + d'un an, un label de durée sans rien faire

D'expérience, les relances sont nécessaires. Envoyer un mail et attendre 1 an pour les recontacter, on va nous dire qu'il est passé dans les spams, etc. Une relance par trimestre à la limite, il faut aussi qu'on prouve qu'on a voulu informer.

**Comment by Altonss** [comment]
@AntoninCurtit j'ai l'impression que ta template ne fonctionne plus :/

**Comment by AntoninCurtit** [comment]
C'est effectivement le cas, il est d'ailleurs dans la liste des choses à faire. :/
https://github.com/osm-fr/attributions/blob/main/.github/ISSUE_TEMPLATE/experimental-issue.yml

**Comment by AntoninCurtit** [comment]
> @AntoninCurtit j'ai l'impression que ta template ne fonctionne plus :/

- [x] Depuis que le bug a été corrigé je n'ai plus cette impression.

**Comment by vinber** [comment]
> Je vous laisse modifier la description, je n'ai pas accès à cela je crois ^^

@Altonss désolé je ne maitrise pas bienlkes histoires de droits, tu dois pouvoir maintenant faire des modifications. Tu me dis si besoin

**Comment by Altonss** [comment]
J'ai pu faire la modification, si la description ne vous convient pas vous pouvez faire d'autres suggestions :)

**Comment by vinber** [comment]
Petite question, quand je veux ajouter une nouvelle issue, j'ai maintenant 5 propositions (ce qui est forcément un frein !). Cela serait bien d'avoir une seule proposition et donc d'effacer, archiver les autres templates non ?

sI quelqu'un sait faire super, sinon je creuserai (j'ai déja fait donc je dois pouvoir retrouver :) )

**Comment by AntoninCurtit** [comment]
Yes, c'est la dernière tâche de cette liste "À faire" de cette issue. Fusionner les templates, trancher sur ce qu'on garde ou pas.
Je devrais avoir du temps dans 1 heure pour faire ça 😊

**Comment by AntoninCurtit** [comment]
On part sur le nouveau modèle (.yml) et on jette les .md ? Ça vous convient ?

**Comment by vinber** [comment]
oui, que cela ne soit plus visible pour les contributeurs

**Comment by Altonss** [comment]
Qu'en pensez-vous d'ajouter un label "Incertitude OpenStreetMap?" pour signaler qu'on a un doute sur la provenance des données et qu'il s'agit peut-être d'un manque d'attribution?
J'ai déjà rencontré ce cas de figure plusieurs fois, la dernière en date ici: https://github.com/osm-fr/attributions/issues/159

**Comment by AntoninCurtit** [comment]
J'ai peur qu'on finisse par rentrer dans l'étape « overdose » de labels, peut-être qu'on peut juste fusionner ton idée avec « Question » ?

**Comment by vinber** [comment]
et d'ailleurs, ne peut-on pas retirer toutes les possibilités effrayantes que l'on a quand on crée une nouvelle issue https://github.com/osm-fr/attributions/issues/new/choose

![image](https://user-images.githubusercontent.com/890869/157192750-7ef89ef0-8c0a-4da3-ab9b-965d2c32b2a8.png)

et on garde seulement la dernière, "l'expérimental est quand même la plus avancée pour l'instant non" ? https://github.com/osm-fr/attributions/blob/main/.github/ISSUE_TEMPLATE/experimental-issue.yml

**Comment by AntoninCurtit** [comment]
Sisi c'est prévu que je me penche dessus — ça fait un moment. Je vais voir pour faire le tri ce matin. 👍

**Comment by vinber** [comment]
yep, super. je ne me souvenais pas que tu souhaitais te pencher dessus mais c'est parfait :D

**Comment by Altonss** [comment]
> J'ai peur qu'on finisse par rentrer dans l'étape « overdose » de labels, peut-être qu'on peut juste fusionner ton idée avec « Question » ?
> 
> Ex, changer la description :
> 
> ```diff
> - Une question sur les attributions
> + Une question/interrogation sur les attributions
> ```

Ah tu as tout à fait raison! Je n'avais pas vu le label "Question", là est mon erreur xD

**Comment by AntoninCurtit** [comment]
✅ Voilà ! Templates fusionnés, dépôt retravaillé

> Ah tu as tout à fait raison! Je n'avais pas vu le label "Question", là est mon erreur xD

Pas grave ;) Mais tu as raison, on peut mettre `Question/Incertitude`, si ça convient ?

**Comment by AntoninCurtit** [comment]
C'est modifié

J'ai également remplacé "Plan papier ou PDF" par "Plan sur support physique"

**Comment by AntoninCurtit** [comment]
Voilà, après tous ces changements j'en propose encore un petit : Regrouper les labels.

De gauche à droite :
- Actuellement
- Suggestion 1 : Proposition de regroupement par couleur
- Suggestion 2 : Proposition de regroupement par couleur et avec classement « par utilité »

Pour « Carte sur support physique » (anciennement « Plan papier ou PDF »), je me demande si c'est vraiment utile ou non. Et si c'est le cas, est-ce qu'il faudrait créer des attributs « Application » « Site Web » etc.
Contrainte également : GitHub ne nous permet pas de classer les labels manuellement, d'où ~ ma petite ruse ~ d'utiliser des lettres.

(Je suis trop maniaque à bosser sur les labels ?)

![image](https://user-images.githubusercontent.com/30950182/157761107-c083d5fb-4f83-4d91-ab11-43522313dbdb.png)

**Comment by danieldegroot2** [comment]
(Pas important/de priorité élevée) Je propose une question(/label) pour les cartes en ligne pour lesquelles il y a l'attribution mais uniquement visible sur la console web (F12). Il y a quelque temps, l'administrateur du site n'a pas vérifié où l'attribution était visible sur la carte oui/non avant de mettre le site en ligne ( https://github.com/osm-fr/attributions/issues/176#issuecomment-1096775739 , et [un example pas francais](https://www.via.nl/Map)). Cela peut être un accident. Ou bien, par accident, ils ont voulu désactiver l'attribution Leaflet (facultatif), mais ils ont désactivé l'attribution complètement.

**Comment by Altonss** [comment]
> (Pas important/de priorité élevée) Je propose une question(/label) pour les cartes en ligne pour lesquelles il y a l'attribution mais uniquement visible sur la console web (F12). Il y a quelque temps, l'administrateur du site n'a pas vérifié où l'attribution était visible sur la carte oui/non avant de mettre le site en ligne ( [#176 (comment)](https://github.com/osm-fr/attributions/issues/176#issuecomment-1096775739) , et [un example pas francais](https://www.via.nl/Map)). Cela peut être un accident. Ou bien, par accident, ils ont voulu désactiver l'attribution Leaflet (facultatif), mais ils ont désactivé l'attribution complètement.

Malheureusement, je pense que souvent ce n'est pas un accident. Si comme dans [#176 (comment)](https://github.com/osm-fr/attributions/issues/176#issuecomment-1096775739) on voit l'attribution dans la console, mais que celle-ci est cachée, c'est probablement souvent intentionnel. Je peux me tromper et il s'agit peut-être parfois d'une erreur ^^

**Comment by AntoninCurtit** [comment]
Il n'y a jamais de 100 %, toujours des exceptions. « L'oubli » ou le fait que l'attribution soit cachée est parfois volontaire, parfois non.

La proposition est intéressante, je suis indécis car ça ajoute encore des labels, qu'une attribution qui n'est pas présente n'est pas présente et peu importe les raisons techniques, bref tout un tas d'arguments qui nous avancent pas...

Mais on peu envisager un changement dans les labels existants :
```diff
- Attribution « OSM » (Attribution insuffisante)
+ Attribution insuffisante (« OSM », présente mais cachée...)
```

Entre parenthèses, la description qui accompagne le label.

Vos avis ?

**Comment by vinber** [comment]
bonjour et merci pour ce travail sur les labels !
oui je pense qu'il fait peut-être avoir des labels plus générique et renseigné ensuite les détails dans la description.

Par exemple (cela vient en écrivant ...) 

- tuiles fondations, osm-fr, services bénévoles ...
- tuiles services payants type mapbox, maptiler, ...

- pas d'attributions visibles (après caché, blanc sur blanc, nécessite un clic ... c'est plutôt dans la description)
- attributions insuffisantes (nécessite un clic alors que d'autres attributions sont visibles sans, pas d'url sur @copyright, ...)

- contacté / pas contacté

oui cela revient donc à ton ABCDE @AntoninCurtit, qui est intéressant, sans doute à associer à des couleurs effectivement pour la lecture mais même à simplifier et réserver les "détails à la description".

Et après je me dis que nous pourrions nous faire une semaine 'Contactons les" pour faire descendre la pile des Non Contacté ?

**Comment by AntoninCurtit** [comment]
Bonjour, désolé pour le délai de réponse...
Après on peut aussi se demander l'utilité de certains labels (ex : pour des stats ?) tellement ils sont pointus. KISS ?
Comme tu l'as dit, certaines informations peuvent être dans le signalement en lui-même, quitte à améliorer encore les templates, pas forcément utile d'avoir un label pour tout. Une recherche avec les mots dans le signalement nous sortira les bons résultats aussi.

Bonne suggestion, l'idée de la semaine pour entamer les prises de contact ! Ça motive, et ça permet de réfléchir à plusieurs sur certains cas épineux.
On a 48 signalements "Non contactés" (encore que, car X signalements peuvent être liés à la même agence), on pourrait se diviser ça mettons en 3, et se faire ça en une aprem. 😃

**Comment by benoit-dd** [comment]
Serait-il possible d'avoir un template pour les agences de communication? Pour les distinguer des cas particuliers des sites qu'elles réalisent? (ex #91 ; #27 ; #390 )

**Comment by vinber** [comment]
>  il faudrait que les signalements aient leur espace dédié. Qu'ils ne soient pas noyés sous 400 autres sujets sans lien.

oui j'imagine bien un espace dédié, dans la catégorie Utiliser, il pourrait y avoir une catégorie Attributions

je ne sais pas exactement pour la question des éléments fermés, mais il existe la possibilité de noter qu'une question à trouver solution, ce qui pourrait en partie répondre à ce besoin

les mots clés et étiquettes, la recherche, la fluidité sont assez intéressante je trouve sur discourse, je ne sais pas si on peut avoir la granularité de filtres qu'il y a sur github, la partie lien marche, si dans sujet 1 on cite sujet 2, alors dans sujet 2 on sait que sujet 1 l'a cité

**Comment by vinber** [comment]
oui si tu veux évidemment, moi il n'y a rien de pressé. effectivement je me dis que petit à petit c'est plus simple d'avoir une entrée mais la diversité ne me dérange pas non plus :)

**Comment by Jean-BaptisteC** [comment]
Avec la création du nouveau dépot de la fondation ne serait-il pas pertinent de créer un nouveau label
Soit pour indiquer qu'un ticket est créé chez eux, soit pour indiquer que le site est banni (avec un label similaire à marquage ajouté ?)

**Comment by Jean-BaptisteC** [comment]
Je viens de rajouter un hyperlien vers le dépôt de la fondation pour le suivi des manques d'attributions dans les ressources du readme.

**Comment by Jean-BaptisteC** [comment]
J'ai renommé le tag tuiles openriverboat en tuiles Mapbox, car aucune issue utilise ces tuiles. Et trier les issues Mapbox permettera de mieux cibler où mettre nos efforts pour espérer que les manques d'attributions soient corrigés

**Comment by Jean-BaptisteC** [comment]
Mapbox a enfin mise à jour son lien vers la page copyright 🎊

**Comment by Jean-BaptisteC** [comment]
Sur tous les sites qui utilisent des Tuiles Mapbox, ça s'applique sans mise à a a jour, mais je suppose que c'est quelqu'un de la communauté qui leur a fait un ticket

**Comment by NathanBnm** [comment]
J'avais fait un ticket mais il n'a pas bougé depuis (https://github.com/mapbox/mapbox-gl-js/issues/13381)

**Comment by Jean-BaptisteC** [comment]
osm Italia, utilise un bot pour faire un rappel automatique à une certaine date, qu'en pensez vous?
https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/issues/126

**Comment by NathanBnm** [comment]
C'est une bonne idée on pourrait le paramétrer en fonction des tags

**Comment by Jean-BaptisteC** [comment]
C'est en prod, voici la syntaxe https://github.com/agrc/reminder-action
Le fonctionnement est assez limité, on ne peut pas en paramétrer automatiquement.

**Comment by NathanBnm** [comment]
Je rencontre de temps en temps des sites qui n'ont aucun moyen de contact. Ce serait intéressant de les différencier avec un label dédié.

**Comment by Jean-BaptisteC** [comment]
Je viens de créer un label `Tuiles custom` pour les sites qui génèrent et hébergent les tuiles eux mêmes
