### ISSUE TITLE
Live Tracking Site of "Tour de France" - incomplete / missing attribution

### ISSUE THREAD

**Issue by sakudo** [osm-fr/attributions#326]
### Ce signalement concerne…

Live tracking of **Tour de France** is probably using a map based on OSM. Please verify.
- [ ] https://racecenter.letour.fr/de/livetracking/1
- [ ] https://racecenter.letour.fr/de/livetracking/2
- [ ] etc for the following stages

Attribution only states "Leaflet (c) ESRI".

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsables contacté le 2.7.23
  - Contacté par Email contact@aso.fr, DPO@amaury.com, and deux contacts de presse: christophe.morel@aso.fr and ftiano@aso.fr
  - Par Twitter: https://twitter.com/SamuelKutter/status/1675478618590289921

**Comment by mlep** [comment]
Isn't the map the one of ESRI (as indicated)?

**Comment by sakudo** [comment]
If so, then of course, it is not an issue.

**Comment by sakudo** [comment]
Then, of course, it is not an issue.
